import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title className=''>Legends rotation - Ghost of Tsushima</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='h-screen w-screen overflow-clip bg-main_bg bg-cover bg-center font-Teko font-teko'>
        <div className='flex justify-center items-center bg-black w-screen h-screen absolute top-0 left-0 bg-opacity-50 z-10'>
          <button className='px-12 py-2 bg-black hover:bg-[#CF0A0A] transition-all duration-300 rounded-md text-white text-4xl'>
            Create rotation
          </button>
        </div>
      </div>
    </>
  );
}
