import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title className=''>Legends rotation - Ghost of Tsushima</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-main_bg text-red-600 w-screen h-screen'>ola</div>
    </>
  );
}
